name: db_diff
services:
  db1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: 'Qwerty123!'
      ACCEPT_EULA: 'Y'
    ports:
    - "1431:1433"
    volumes:
    #- ./data/db1/data:/var/opt/mssql/data
    #- ./data/db1/log:/var/opt/mssql/log
    #- ./data/db1/secrets:/var/opt/mssql/secrets
    - ./data/backup:/mnt/backup
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - dev_network      
  db2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: 'Qwerty123!'
      ACCEPT_EULA: 'Y'
    ports:
    - "1432:1433"
    volumes:
    #- ./data/db2/data:/var/opt/mssql/data
    #- ./data/db2/log:/var/opt/mssql/log
    #- ./data/db2/secrets:/var/opt/mssql/secrets
    - ./data/backup:/mnt/backup
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - dev_network      
  differ:
    image: differ
    build: ./docker_images/differ
    environment:
      MSSQL_SA_PASSWORD: 'Qwerty123!'    
    command: sh -c /mnt/backup/init_db.sh
    volumes:
      - ./data/backup:/mnt/backup
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    privileged: true # Required for Docker-in-Docker      
    depends_on:
      - db1
      - db2
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge      

